language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install chardet
  - pip install flake8
  - pip install pydocstyle
  - pip install logbook
# command to run tests
script:
  - python EricPackagesChecker.py
  - flake8 . --max-line-length=120
  - pydocstyle .
