language: python
python:
  - "3.6.3"
# command to install dependencies
install:
  - pip install chardet
  - pip install logbook
# command to run tests
script:
  - python "tests/eric_run_tests.py"
  # - python "tests/eric_body.py"
  # - python "tests/eric_head.py"
  # - python "tests/eric_asterisks.py"
